author: "Joannis Orlandos, Laurent Gaches and Robbert Brandsma"
module: MongoKitten
readme: README.md
github_url: https://github.com/OpenKitten/MongoKitten
xcodebuild_arguments:
  - "-scheme"
  - "MongoKitten-Package"
dash_url: http://openkitten.github.io/MongoKitten/MongoKitten.xml
