os:
  - linux
language: generic
sudo: required
dist: trusty
services: 
  - docker
script:
  - eval "$(curl -sL https://raw.githubusercontent.com/OpenKitten/Mongo-Assets/master/travisci-31)"
  - eval "$(curl -sL https://raw.githubusercontent.com/OpenKitten/Mongo-Assets/master/codecov)"
